function pkgJson(projectName, needsAuth) {
  return JSON.stringify(
    {
      name: projectName.toLowerCase().replace(/[^a-z0-9-]+/g, "-"),
      version: "1.0.0",
      private: true,
      main: "src/server.js",
      scripts: {
        start: "node src/server.js",
        test: "jest --runInBand --forceExit",
      },
      dependencies: {
        express: "^4.19.2",
        mongoose: "^8.5.1",
        cors: "^2.8.5",
        dotenv: "^16.4.5",
        "express-validator": "^7.2.0",
        ...(needsAuth ? { jsonwebtoken: "^9.0.2", bcryptjs: "^2.4.3" } : {}),
      },
      devDependencies: {
        jest: "^29.7.0",
        supertest: "^7.0.0",
      },
    },
    null,
    2
  );
}

function envExample(needsAuth) {
  return [
    "PORT=4000",
    "MONGODB_URI=mongodb://localhost:27017/app",
    ...(needsAuth ? ["JWT_SECRET=changeme_use_a_long_random_secret"] : []),
  ].join("\n") + "\n";
}

function dockerfile() {
  return `FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY . .
EXPOSE 4000
CMD ["node", "src/server.js"]
`;
}

function readme(projectName, analysis) {
  return `# ${projectName}

Generated by BackendForge AI.

## Run

\`\`\`
npm install
cp .env.example .env
npm start
\`\`\`

## Test

\`\`\`
npm test
\`\`\`

## Endpoints

${analysis.endpoints.map((e) => `- \`${e.method} ${e.path}\`${e.auth ? " (auth required)" : ""}`).join("\n")}
`;
}

function dbConfig() {
  return `const mongoose = require("mongoose");

async function connectDB(uri) {
  await mongoose.connect(uri);
  console.log("[db] connected");
}

module.exports = { connectDB };
`;
}

function errorHandler() {
  return `function errorHandler(err, req, res, next) {
  const statusCode = err.statusCode && Number.isInteger(err.statusCode) ? err.statusCode : 500;
  const message = err.message || "Internal Server Error";
  if (statusCode >= 500) {
    console.error(err);
  }
  res.status(statusCode).json({ error: message });
}

module.exports = { errorHandler };
`;
}

function notFound() {
  return `function notFound(req, res, next) {
  res.status(404).json({ error: \`Route not found: \${req.method} \${req.originalUrl}\` });
}

module.exports = { notFound };
`;
}

function appJs({ needsAuth, primaryEntities }) {
  const routeImports = [
    needsAuth ? `const authRoutes = require("./routes/authRoutes");` : null,
    ...primaryEntities.map((e) => `const ${e.toLowerCase()}Routes = require("./routes/${e.toLowerCase()}Routes");`),
  ]
    .filter(Boolean)
    .join("\n");

  const routeMounts = [
    needsAuth ? `app.use("/api/auth", authRoutes);` : null,
    ...primaryEntities.map((e) => {
      const plural = e.toLowerCase() + (e.toLowerCase().endsWith("s") ? "es" : "s");
      return `app.use("/api/${plural}", ${e.toLowerCase()}Routes);`;
    }),
  ]
    .filter(Boolean)
    .join("\n");

  return `const express = require("express");
const cors = require("cors");
${routeImports}
const { errorHandler } = require("./middleware/errorHandler");
const { notFound } = require("./middleware/notFound");

function createApp() {
  const app = express();
  app.use(cors());
  app.use(express.json());

  app.get("/health", (req, res) => res.json({ status: "ok" }));

  ${routeMounts}

  app.use(notFound);
  app.use(errorHandler);

  return app;
}

module.exports = { createApp };
`;
}

function serverJs() {
  return `require("dotenv").config();
const { createApp } = require("./app");
const { connectDB } = require("./config/db");

const PORT = process.env.PORT || 4000;
const MONGODB_URI = process.env.MONGODB_URI;

async function start() {
  await connectDB(MONGODB_URI);
  const app = createApp();
  const server = app.listen(PORT, () => {
    console.log(\`[server] listening on port \${PORT}\`);
  });
  return server;
}

if (require.main === module) {
  start().catch((err) => {
    console.error("[server] failed to start", err);
    process.exit(1);
  });
}

module.exports = { start };
`;
}

module.exports = { pkgJson, envExample, dockerfile, readme, dbConfig, errorHandler, notFound, appJs, serverJs };